### PR TITLE
[10.0] [ADD] setup for web_timeline

### PR DESCRIPTION
**Pull request by ThomasBinsfeld**
https://github.com/OCA/web/pull/521

### CODE REVIEW

**Comment by LeartS** [comment]
Hi Thomas, thanks for your pull request!

I'm not clear on what this PR is about, can you explain or link to a discussion on this?

**Comment by ThomasBinsfeld** [comment]
HI @LeartS. It's the setup folder allowing us to install this module using pypi. When merged in the 10.0 branch of the repo, this setup will be automatically added anyway (nightly). See [here](https://github.com/acsone/web/tree/10.0/setup). If you're interested, see the documentation [here](https://pypi.python.org/pypi/setuptools-odoo) :smiley:

**Comment by ThomasBinsfeld** [comment]
@LeartS ping

**Comment by LeartS** [comment]
Merged, thanks. Do you happen to have a link to a discussion in the OCA mailing list about this?

**Pull request merged**
